#/appspec.yml
version: 0.0
os: linux
files:
  - source: /
    destination: /app/partner/server

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: initialize.sh
      runas: ubuntu

  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu
  # ValidateService:
  #   - location: /healthCheck.sh
  #     runas: ubuntu
  #     # ubuntu의 $HOME 환경변수를 이용해보려고 runas ubuntu