spring:
  datasource-partner:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://wrightbrothers-partner-dev.cf22cofp8pqh.ap-northeast-2.rds.amazonaws.com/partner?useSSL=false&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&allowMultiQueries=true
    username: admin
    password: pszqU1Be8LcZDWunv19N
    maximumPoolSize: 5
  datasource-admin:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://wrightbrothers-dev-admin.c9lwghctzixx.ap-northeast-2.rds.amazonaws.com:3306/wrightbrothers?useSSL=false&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&allowMultiQueries=true
    username: admin
    password: rBEdceIdPrQMaHrQVcZj
    maximumPoolSize: 5

cloud:
  aws:
    s3:
      bucket: wb-storage-dev
    region:
      static: ap-northeast-2
    sqs:
      auto: false
      partner: DEV-PARTNER-PRODUCT.fifo
    sns:
      arn: 'arn:aws:sns:ap-northeast-2:094301229591:'
      auto: false
      ack: DEV-ACKMSG.fifo
      partner: DEV-PARTNER-PRODUCT.fifo
system:
  file:
    temp:
      # 임시 파일 저장 위치
      path: /Users/chals/partner_project/file_temp