logging:
  config: classpath:logback.xml
  level:
    org:
      springframework:
        boot:
          autoconfigure: INFO
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR

spring:
  datasource-partner:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://wrightbrothers-partner-dev.c9lwghctzixx.ap-northeast-2.rds.amazonaws.com:3306/partner?useSSL=false&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&allowMultiQueries=true
    username: admin
    password: fstGwe2VogETXwjY4qH8
    maximumPoolSize: 10
  datasource-admin:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://admin2prodread.c9lwghctzixx.ap-northeast-2.rds.amazonaws.com:3306/wrightbrothers?useSSL=false&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&allowMultiQueries=true
    username: admin
    password: rBEdceIdPrQMaHrQVcZj
    maximumPoolSize: 10

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

cloud:
  aws:
    credentials:
      accessKey: AKIARL5GKSIL5OK4DO5V
      secretKey: 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
    s3:
      bucket: wb-storage-dev
    region:
      static: ap-northeast-2
    stack:
      auto: false

System:
  File:
    Temp:
      Path: "/partner_project/file_temp"

jwt:
  secret-key: aYEFtKMCn0xCg5caH1nnFuHfdAB0lBOvdonxq80VqOGNnG6QcyagXWOLrUdqJnzexUXYceMhGNFNYsA6rblSibUEh0yRsJ3XO1um1iMdoekOPzj4zKlokcu9TxTbz5DHYVLkqX3q9JrLgbLZFXD8ynOHfRHRL5Ge64iFZBVm9X517fwZrNornOmK2L7hUz10SgZpxAz6
  validation-time:
    token: 60 #MIN(분)
    refresh-token: 60 #MIN(분)

