server:
  port: 8090
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: html

cloud:
  aws:
    s3:
      bucket: wb-storage-dev
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: AKIARL5GKSIL5OK4DO5V
      secretKey: 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
    ses:
      accessKey: AKIARL5GKSILRUJFMCMR
      secretKey: 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

system:
  name: PARTNER
  mail:
    # AWS SES 메일 발송자
    sender: noreply@wrightbrothers.kr
  lang: ko

jwt:
  secret-key: aYEFtKMCn0xCg5caH1nnFuHfdAB0lBOvdonxq80VqOGNnG6QcyagXWOLrUdqJnzexUXYceMhGNFNYsA6rblSibUEh0yRsJ3XO1um1iMdoekOPzj4zKlokcu9TxTbz5DHYVLkqX3q9JrLgbLZFXD8ynOHfRHRL5Ge64iFZBVm9X517fwZrNornOmK2L7hUz10SgZpxAz6
  validation-time:
    access-token-min: 60 #MIN(분)
    refresh-token-min: 60 #MIN(분)

